use std::fmt::Write as _;

use bpmp_contracts::wir::v1::{
    ComparisonOperator, GatewayDirection, HitPolicy, WorkflowIntermediateRepresentation,
    guard_expression, node, unary_test, workflow_literal,
};
use thiserror::Error;

#[allow(clippy::too_many_lines)]
pub(crate) fn generate_rust(
    wir: &WorkflowIntermediateRepresentation,
) -> Result<String, CodegenError> {
    let mut output = String::new();
    writeln!(output, "// Generated by bpmn-compiler. Do not edit.").unwrap();
    writeln!(output, "#![forbid(unsafe_code)]").unwrap();
    writeln!(output, "#![allow(dead_code, unused_variables)]").unwrap();
    writeln!(output, "pub const TENANT_ID: &str = {:?};", wir.tenant_id).unwrap();
    writeln!(
        output,
        "pub const WORKFLOW_TYPE: &str = {:?};",
        wir.workflow_type
    )
    .unwrap();
    writeln!(
        output,
        "pub const WORKFLOW_VERSION: &str = {:?};",
        wir.workflow_version
    )
    .unwrap();
    writeln!(
        output,
        "pub const START_NODE_ID: &str = {:?};",
        wir.start_node_id
    )
    .unwrap();
    output.push_str(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum GatewayKind { Exclusive, Inclusive, Parallel }\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum NodeKind { Start, ServiceTask, DecisionTask, Split(GatewayKind), Join(GatewayKind), End }\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum Operator { Equal, NotEqual, LessThan, LessThanOrEqual, GreaterThan, GreaterThanOrEqual }\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum GuardValue { Boolean(bool), Integer(i64), String(&'static str) }\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum RuntimeValue<'a> { Boolean(bool), Integer(i64), String(&'a str) }\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct Guard { pub variable: &'static str, pub operator: Operator, pub literal: GuardValue }\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct Transition { pub target: &'static str, pub guard: Option<Guard>, pub is_default: bool }\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub struct Node { pub id: &'static str, pub kind: NodeKind, pub transitions: &'static [Transition], pub paired_gateway: Option<&'static str> }\n",
    );

    for (index, encoded) in wir.nodes.iter().enumerate() {
        let (kind, next, paired) = render_node(encoded)?;
        let transitions = render_transitions(encoded)?;
        writeln!(
            output,
            "const TRANSITIONS_{index}: &[Transition] = &{transitions};"
        )
        .unwrap();
        writeln!(
            output,
            "const NODE_{index}: Node = Node {{ id: {:?}, kind: {kind}, transitions: TRANSITIONS_{index}, paired_gateway: {paired} }};",
            encoded.id
        )
        .unwrap();
        let _ = next;
    }
    writeln!(output, "pub const NODES: &[Node] = &[").unwrap();
    for index in 0..wir.nodes.len() {
        writeln!(output, "    NODE_{index},").unwrap();
    }
    output.push_str(
        "];\n\
         pub fn node(id: &str) -> Option<&'static Node> { NODES.iter().find(|node| node.id == id) }\n\
         #[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum EvalError { UnknownNode, MissingVariable, TypeMismatch, AmbiguousExclusive, NoBranch }\n\
         pub fn enabled_targets<'a>(id: &str, variables: &std::collections::BTreeMap<&str, RuntimeValue<'a>>) -> Result<Vec<&'static str>, EvalError> {\n\
             let node = node(id).ok_or(EvalError::UnknownNode)?;\n\
             let mut selected = Vec::new();\n\
             let mut default = None;\n\
             for transition in node.transitions {\n\
                 if transition.is_default { default = Some(transition.target); continue; }\n\
                 if let Some(guard) = transition.guard {\n\
                     let value = variables.get(guard.variable).ok_or(EvalError::MissingVariable)?;\n\
                     if evaluate_guard(value, guard)? { selected.push(transition.target); }\n\
                 } else { selected.push(transition.target); }\n\
             }\n\
             if selected.is_empty() { if let Some(target) = default { selected.push(target); } }\n\
             if matches!(node.kind, NodeKind::Split(GatewayKind::Exclusive)) && selected.len() > 1 { return Err(EvalError::AmbiguousExclusive); }\n\
             if !node.transitions.is_empty() && selected.is_empty() { return Err(EvalError::NoBranch); }\n\
             Ok(selected)\n\
         }\n\
         fn evaluate_guard(value: &RuntimeValue<'_>, guard: Guard) -> Result<bool, EvalError> {\n\
             use std::cmp::Ordering;\n\
             let ordering = match (value, guard.literal) {\n\
                 (RuntimeValue::Boolean(left), GuardValue::Boolean(right)) => left.cmp(&right),\n\
                 (RuntimeValue::Integer(left), GuardValue::Integer(right)) => left.cmp(&right),\n\
                 (RuntimeValue::String(left), GuardValue::String(right)) => left.cmp(&right),\n\
                 _ => return Err(EvalError::TypeMismatch),\n\
             };\n\
             Ok(match guard.operator {\n\
                 Operator::Equal => ordering == Ordering::Equal, Operator::NotEqual => ordering != Ordering::Equal,\n\
                 Operator::LessThan => ordering == Ordering::Less, Operator::LessThanOrEqual => ordering != Ordering::Greater,\n\
                 Operator::GreaterThan => ordering == Ordering::Greater, Operator::GreaterThanOrEqual => ordering != Ordering::Less,\n\
             })\n\
         }\n",
    );
    writeln!(
        output,
        "pub const DECISION_TABLE_IDS: &[&str] = &{:?};",
        wir.decision_tables
            .iter()
            .map(|table| table.id.as_str())
            .collect::<Vec<_>>()
    )
    .unwrap();
    writeln!(
        output,
        "pub const CASE_MODEL_IDS: &[&str] = &{:?};",
        wir.case_models
            .iter()
            .map(|model| model.id.as_str())
            .collect::<Vec<_>>()
    )
    .unwrap();
    output.push_str(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n\
         pub enum DecisionError { UnknownTable, MissingInput, TypeMismatch, Ambiguous, NoRule }\n\
         pub type DecisionOutput = Vec<(&'static str, GuardValue)>;\n",
    );
    render_decision_functions(wir, &mut output)?;
    Ok(output)
}

fn render_decision_functions(
    wir: &WorkflowIntermediateRepresentation,
    output: &mut String,
) -> Result<(), CodegenError> {
    output.push_str(
        "pub fn evaluate_decision<'a>(table_id: &str, variables: &std::collections::BTreeMap<&str, RuntimeValue<'a>>) -> Result<DecisionOutput, DecisionError> {\n\
             match table_id {\n",
    );
    for (index, table) in wir.decision_tables.iter().enumerate() {
        writeln!(
            output,
            "        {:?} => decision_{index}(variables),",
            table.id
        )
        .unwrap();
    }
    output.push_str(
        "        _ => Err(DecisionError::UnknownTable),\n\
             }\n\
         }\n",
    );
    for (index, table) in wir.decision_tables.iter().enumerate() {
        let hit_policy = HitPolicy::try_from(table.hit_policy)
            .map_err(|_| CodegenError::InvalidDecisionTable(table.id.clone()))?;
        if matches!(hit_policy, HitPolicy::Unspecified | HitPolicy::Collect) {
            return Err(CodegenError::InvalidDecisionTable(table.id.clone()));
        }
        writeln!(
            output,
            "fn decision_{index}<'a>(variables: &std::collections::BTreeMap<&str, RuntimeValue<'a>>) -> Result<DecisionOutput, DecisionError> {{"
        )
        .unwrap();
        output.push_str("    let mut matched: Option<DecisionOutput> = None;\n");
        for rule in &table.rules {
            if rule.input_tests.len() != table.inputs.len()
                || rule.output_values.len() != table.outputs.len()
            {
                return Err(CodegenError::InvalidDecisionTable(table.id.clone()));
            }
            let conditions = table
                .inputs
                .iter()
                .zip(&rule.input_tests)
                .map(|(input, test)| render_unary_test(&input.name, test))
                .collect::<Result<Vec<_>, _>>()?;
            let outputs = table
                .outputs
                .iter()
                .zip(&rule.output_values)
                .map(|(definition, value)| {
                    Ok(format!(
                        "({:?}, {})",
                        definition.name,
                        render_workflow_literal(value)?
                    ))
                })
                .collect::<Result<Vec<_>, CodegenError>>()?;
            writeln!(output, "    if {} {{", conditions.join(" && ")).unwrap();
            writeln!(output, "        let output = vec![{}];", outputs.join(", ")).unwrap();
            match hit_policy {
                HitPolicy::First => output.push_str("        return Ok(output);\n"),
                HitPolicy::Unique => output.push_str(
                    "        if matched.is_some() { return Err(DecisionError::Ambiguous); }\n\
                     matched = Some(output);\n",
                ),
                HitPolicy::Unspecified | HitPolicy::Collect => unreachable!(),
            }
            output.push_str("    }\n");
        }
        output.push_str("    matched.ok_or(DecisionError::NoRule)\n}\n");
    }
    output.push_str(
        "fn decision_equal(value: Option<&RuntimeValue<'_>>, literal: GuardValue) -> Result<bool, DecisionError> {\n\
             let value = value.ok_or(DecisionError::MissingInput)?;\n\
             match (value, literal) {\n\
                 (RuntimeValue::Boolean(left), GuardValue::Boolean(right)) => Ok(*left == right),\n\
                 (RuntimeValue::Integer(left), GuardValue::Integer(right)) => Ok(*left == right),\n\
                 (RuntimeValue::String(left), GuardValue::String(right)) => Ok(*left == right),\n\
                 _ => Err(DecisionError::TypeMismatch),\n\
             }\n\
         }\n\
         fn decision_interval(value: Option<&RuntimeValue<'_>>, lower: Option<i64>, upper: Option<i64>) -> Result<bool, DecisionError> {\n\
             let RuntimeValue::Integer(value) = value.ok_or(DecisionError::MissingInput)? else { return Err(DecisionError::TypeMismatch); };\n\
             Ok(lower.is_none_or(|lower| *value >= lower) && upper.is_none_or(|upper| *value <= upper))\n\
         }\n",
    );
    Ok(())
}

fn render_unary_test(
    input_name: &str,
    test: &bpmp_contracts::wir::v1::UnaryTest,
) -> Result<String, CodegenError> {
    match test
        .test
        .as_ref()
        .ok_or_else(|| CodegenError::InvalidDecisionTable(input_name.to_owned()))?
    {
        unary_test::Test::Any(_) => Ok("true".into()),
        unary_test::Test::Equal(value) => Ok(format!(
            "decision_equal(variables.get({:?}), {})?",
            input_name,
            render_workflow_literal(value)?
        )),
        unary_test::Test::IntegerInterval(interval) => Ok(format!(
            "decision_interval(variables.get({:?}), {}, {})?",
            input_name,
            if interval.lower_unbounded {
                "None".into()
            } else {
                format!("Some({})", interval.lower_bound)
            },
            if interval.upper_unbounded {
                "None".into()
            } else {
                format!("Some({})", interval.upper_bound)
            }
        )),
    }
}

fn render_workflow_literal(
    value: &bpmp_contracts::wir::v1::WorkflowLiteral,
) -> Result<String, CodegenError> {
    match value
        .value
        .as_ref()
        .ok_or_else(|| CodegenError::InvalidDecisionTable("missing literal".into()))?
    {
        workflow_literal::Value::BooleanValue(value) => Ok(format!("GuardValue::Boolean({value})")),
        workflow_literal::Value::IntegerValue(value) => Ok(format!("GuardValue::Integer({value})")),
        workflow_literal::Value::StringValue(value) => Ok(format!("GuardValue::String({value:?})")),
    }
}

fn render_transitions(encoded: &bpmp_contracts::wir::v1::Node) -> Result<String, CodegenError> {
    let kind = encoded
        .kind
        .as_ref()
        .ok_or_else(|| CodegenError::MissingNodeKind(encoded.id.clone()))?;
    let transitions = match kind {
        node::Kind::Start(node) => vec![unconditional(&node.next_node_id)],
        node::Kind::ServiceTask(node) => vec![unconditional(&node.next_node_id)],
        node::Kind::DecisionTask(node) => vec![unconditional(&node.next_node_id)],
        node::Kind::ExclusiveGateway(node) => node
            .transitions
            .iter()
            .map(render_transition)
            .collect::<Result<_, _>>()?,
        node::Kind::ParallelGateway(node) => node
            .target_node_ids
            .iter()
            .map(|target| unconditional(target))
            .collect(),
        node::Kind::InclusiveGateway(node) => match GatewayDirection::try_from(node.direction) {
            Ok(GatewayDirection::Split) => node
                .transitions
                .iter()
                .map(render_transition)
                .collect::<Result<_, _>>()?,
            Ok(GatewayDirection::Join) => vec![unconditional(&node.next_node_id)],
            Ok(GatewayDirection::Unspecified) | Err(_) => {
                return Err(CodegenError::InvalidGatewayDirection(node.direction));
            }
        },
        node::Kind::End(_) => Vec::new(),
    };
    Ok(format!("[{}]", transitions.join(", ")))
}

fn unconditional(target: &str) -> String {
    format!("Transition {{ target: {target:?}, guard: None, is_default: false }}")
}

fn render_transition(
    transition: &bpmp_contracts::wir::v1::ConditionalTransition,
) -> Result<String, CodegenError> {
    let guard = transition.guard.as_ref().map(render_guard).transpose()?;
    Ok(format!(
        "Transition {{ target: {:?}, guard: {}, is_default: {} }}",
        transition.target_node_id,
        guard.map_or_else(|| "None".into(), |guard| format!("Some({guard})")),
        transition.is_default
    ))
}

fn render_guard(guard: &bpmp_contracts::wir::v1::GuardExpression) -> Result<String, CodegenError> {
    let operator = match ComparisonOperator::try_from(guard.operator) {
        Ok(ComparisonOperator::Equal) => "Operator::Equal",
        Ok(ComparisonOperator::NotEqual) => "Operator::NotEqual",
        Ok(ComparisonOperator::LessThan) => "Operator::LessThan",
        Ok(ComparisonOperator::LessThanOrEqual) => "Operator::LessThanOrEqual",
        Ok(ComparisonOperator::GreaterThan) => "Operator::GreaterThan",
        Ok(ComparisonOperator::GreaterThanOrEqual) => "Operator::GreaterThanOrEqual",
        Ok(ComparisonOperator::Unspecified) | Err(_) => {
            return Err(CodegenError::InvalidGuard(guard.variable.clone()));
        }
    };
    let literal = match guard.literal.as_ref() {
        Some(guard_expression::Literal::BooleanValue(value)) => {
            format!("GuardValue::Boolean({value})")
        }
        Some(guard_expression::Literal::IntegerValue(value)) => {
            format!("GuardValue::Integer({value})")
        }
        Some(guard_expression::Literal::StringValue(value)) => {
            format!("GuardValue::String({value:?})")
        }
        None => return Err(CodegenError::InvalidGuard(guard.variable.clone())),
    };
    Ok(format!(
        "Guard {{ variable: {:?}, operator: {operator}, literal: {literal} }}",
        guard.variable
    ))
}

fn render_node(
    encoded: &bpmp_contracts::wir::v1::Node,
) -> Result<(String, String, String), CodegenError> {
    let kind = encoded
        .kind
        .as_ref()
        .ok_or_else(|| CodegenError::MissingNodeKind(encoded.id.clone()))?;
    let rendered = match kind {
        node::Kind::Start(start) => (
            "NodeKind::Start".into(),
            format!("[{:?}]", start.next_node_id),
            "None".into(),
        ),
        node::Kind::ServiceTask(task) => (
            "NodeKind::ServiceTask".into(),
            format!("[{:?}]", task.next_node_id),
            "None".into(),
        ),
        node::Kind::DecisionTask(task) => (
            "NodeKind::DecisionTask".into(),
            format!("[{:?}]", task.next_node_id),
            "None".into(),
        ),
        node::Kind::ExclusiveGateway(gateway) => {
            validate_guards(&encoded.id, &gateway.transitions)?;
            (
                "NodeKind::Split(GatewayKind::Exclusive)".into(),
                format!(
                    "{:?}",
                    gateway
                        .transitions
                        .iter()
                        .map(|transition| transition.target_node_id.as_str())
                        .collect::<Vec<_>>()
                ),
                "None".into(),
            )
        }
        node::Kind::ParallelGateway(gateway) => {
            let direction = direction(gateway.direction)?;
            (
                format!("NodeKind::{direction}(GatewayKind::Parallel)"),
                format!("{:?}", gateway.target_node_ids),
                format!("Some({:?})", gateway.paired_gateway_id),
            )
        }
        node::Kind::InclusiveGateway(gateway) => {
            let direction = direction(gateway.direction)?;
            validate_guards(&encoded.id, &gateway.transitions)?;
            let next = if matches!(
                GatewayDirection::try_from(gateway.direction),
                Ok(GatewayDirection::Split)
            ) {
                gateway
                    .transitions
                    .iter()
                    .map(|transition| transition.target_node_id.as_str())
                    .collect::<Vec<_>>()
            } else {
                vec![gateway.next_node_id.as_str()]
            };
            (
                format!("NodeKind::{direction}(GatewayKind::Inclusive)"),
                format!("{next:?}"),
                format!("Some({:?})", gateway.paired_gateway_id),
            )
        }
        node::Kind::End(_) => ("NodeKind::End".into(), "[]".into(), "None".into()),
    };
    Ok(rendered)
}

fn direction(value: i32) -> Result<&'static str, CodegenError> {
    match GatewayDirection::try_from(value) {
        Ok(GatewayDirection::Split) => Ok("Split"),
        Ok(GatewayDirection::Join) => Ok("Join"),
        Ok(GatewayDirection::Unspecified) | Err(_) => {
            Err(CodegenError::InvalidGatewayDirection(value))
        }
    }
}

fn validate_guards(
    node_id: &str,
    transitions: &[bpmp_contracts::wir::v1::ConditionalTransition],
) -> Result<(), CodegenError> {
    for transition in transitions {
        let Some(guard) = &transition.guard else {
            continue;
        };
        ComparisonOperator::try_from(guard.operator)
            .map_err(|_| CodegenError::InvalidGuard(node_id.to_owned()))?;
        if matches!(
            ComparisonOperator::try_from(guard.operator),
            Ok(ComparisonOperator::Unspecified)
        ) || guard.literal.is_none()
            || matches!(guard.literal, Some(guard_expression::Literal::StringValue(ref value)) if value.contains('\0'))
        {
            return Err(CodegenError::InvalidGuard(node_id.to_owned()));
        }
    }
    Ok(())
}

#[derive(Debug, Error)]
pub enum CodegenError {
    #[error("WIR node {0} has no kind")]
    MissingNodeKind(String),
    #[error("gateway direction tag {0} is invalid")]
    InvalidGatewayDirection(i32),
    #[error("gateway {0} contains an invalid typed guard")]
    InvalidGuard(String),
    #[error("decision table {0} is invalid for Rust generation")]
    InvalidDecisionTable(String),
}
